import pytest
import html
from gptscan import parse_report_content

def test_parse_html_report_basic():
    """Test parsing a standard HTML report generated by the tool."""
    html_content = """
    <table>
        <tr class="high-risk">
            <td>test.py</td>
            <td>10</td>
            <td>85%</td>
            <td>
                <strong>Admin:</strong> This is malicious.<br>
                <strong>User:</strong> Be careful.
            </td>
            <td><pre><code>print("hack")</code></pre></td>
        </tr>
    </table>
    """
    results = parse_report_content(html_content, filename_hint="report.html")

    assert len(results) == 1
    assert results[0]["path"] == "test.py"
    assert results[0]["line"] == "10"
    assert results[0]["own_conf"] == "85%"
    assert results[0]["admin_desc"] == "This is malicious."
    assert results[0]["end-user_desc"] == "Be careful."
    assert results[0]["snippet"] == 'print("hack")'

def test_parse_html_report_escaped_content():
    """Test that HTML entities are correctly unescaped during import."""
    path = "my scripts/test&demo.js"
    snippet = "if (a < 10 && b > 20) { alert('Hacked!'); }"
    admin = "Found <script> tag injection."

    html_content = f"""
    <table>
        <tr>
            <td>{html.escape(path)}</td>
            <td>1</td>
            <td>50%</td>
            <td>
                <strong>Admin:</strong> {html.escape(admin)}<br>
                <strong>User:</strong> Alert.
            </td>
            <td><pre><code>{html.escape(snippet)}</code></pre></td>
        </tr>
    </table>
    """
    results = parse_report_content(html_content)

    assert len(results) == 1
    assert results[0]["path"] == path
    assert results[0]["snippet"] == snippet
    assert results[0]["admin_desc"] == admin

def test_parse_html_report_multiple_rows():
    """Test parsing multiple rows from an HTML report."""
    html_content = """
    <table>
        <tr><th>Path</th><th>Line</th><th>Conf</th><th>Analysis</th><th>Snippet</th></tr>
        <tr>
            <td>file1.py</td>
            <td>1</td>
            <td>90%</td>
            <td><strong>Admin:</strong> Bad.<br><strong>User:</strong> Bad.</td>
            <td><pre><code>eval(x)</code></pre></td>
        </tr>
        <tr class="medium-risk">
            <td>file2.js</td>
            <td>5</td>
            <td>60%</td>
            <td><strong>Admin:</strong> Suspicious.<br><strong>User:</strong> Check it.</td>
            <td><pre><code>os.system("ls")</code></pre></td>
        </tr>
    </table>
    """
    results = parse_report_content(html_content)

    assert len(results) == 2
    assert results[0]["path"] == "file1.py"
    assert results[1]["path"] == "file2.js"
    assert results[1]["line"] == "5"

def test_parse_html_report_no_user_notes():
    """Test parsing when User notes are missing in the Analysis column."""
    html_content = """
    <table>
        <tr>
            <td>test.py</td>
            <td>1</td>
            <td>50%</td>
            <td>
                <strong>Admin:</strong> Only admin notes here.
            </td>
            <td><pre><code>snippet</code></pre></td>
        </tr>
    </table>
    """
    results = parse_report_content(html_content)

    assert len(results) == 1
    assert results[0]["admin_desc"] == "Only admin notes here."
    assert results[0]["end-user_desc"] == ""

def test_parse_html_report_multiline_notes():
    """Test that <br> tags in notes are converted back to newlines."""
    html_content = """
    <table>
        <tr>
            <td>test.py</td>
            <td>1</td>
            <td>50%</td>
            <td>
                <strong>Admin:</strong> Line 1<br>Line 2<br>
                <strong>User:</strong> User Line 1<br>User Line 2
            </td>
            <td><pre><code>snippet</code></pre></td>
        </tr>
    </table>
    """
    results = parse_report_content(html_content)

    assert len(results) == 1
    assert results[0]["admin_desc"] == "Line 1\nLine 2"
    assert results[0]["end-user_desc"] == "User Line 1\nUser Line 2"

def test_parse_html_unsupported_extension():
    """Test that unsupported extensions raise ValueError if hinted."""
    with pytest.raises(ValueError, match="Unsupported file extension"):
        parse_report_content("<html></html>", filename_hint="report.txt")
